#!/usr/bin/env bash -eo pipefail

# Usage example:
# ./example-1-test-ssh-port/complex-ssh-test federico example.com ~/.ssh/id_rsa_federico_wyeworks | tee /dev/tty | grep "FAIL" | wc -l

function bash_test() {
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  NC='\033[0m'

  echo -ne "${NC}$1"

  if eval "${@:2}"; then
    echo -e " -> ${GREEN}OK"
  else
    echo -e " -> ${RED}FAIL"
  fi
}

user=$1
host=$2
key_file=$3

bash_test "Testing if ssh port (22) is open" "nmap $host -PN -p ssh | grep -q open"
bash_test "Testing if connection can be established" ssh -o BatchMode=yes -o ConnectTimeout=10 -i "$key_file" -q "$user"@"$host" exit
