Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provision 'ansible' do |ansible|
    ansible.compatibility_mode = '2.0'
    ansible.playbook = 'playbook.yml'
    ansible.become = true
    ansible.become_user = 'root'
  end
end
