version: 2
references:

base_image: &base_image
  circleci/ruby:2.5.1

working_directory: &working_directory
  ~/example

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

restore_dependencies: &restore_dependencies
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - v1-dependencies-

save_dependencies: &save_dependencies
  save_cache:
    paths:
      - ./vendor/bundle
    key: v1-dependencies-{{ checksum "Gemfile.lock" }}

bundle_install: &bundle_install
  run:
    name: Install bundle dependencies
    command: bundle install --jobs=4 --retry=3 --path vendor/bundle

jobs:
  unit:
    <<: *default_config
    steps:
      - checkout
      - *restore_dependencies
      - *bundle_install
      - *save_dependencies
      - *save_repo
      - run:
          name: Rubocop
          command: bundle exec rubocop

  integration-ubuntu-1804:
    <<: *default_config
    steps:
      - *restore_repo
      - *restore_dependencies
      - *bundle_install
      - run:
          name: Setup test-kitchen
          command: .circleci/kitchen/setup
      - run:
          name: Run integration tests on AWS
          command: |
            SUITE_NAME=$(bundle exec kitchen list -b | grep 1804)
            bundle exec kitchen test "$SUITE_NAME"

  integration-ubuntu-1404:
    <<: *default_config
    steps:
      - *restore_repo
      - *restore_dependencies
      - *bundle_install
      - run:
          name: Setup test-kitchen
          command: .circleci/kitchen/setup
      - run:
          name: Run integration tests on AWS
          command: |
            SUITE_NAME=$(bundle exec kitchen list -b | grep 1404)
            bundle exec kitchen test "$SUITE_NAME"

workflows:
  version: 2
  unit_and_integration:
    jobs:
      - unit
      - integration-ubuntu-1404:
          requires:
            - unit
      - integration-ubuntu-1804:
          requires:
            - unit
